bucky/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls'))
]

music/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.index, name='index'),

    # /music/5/  <- /music/album + /album_id
    url(
        r'^album/(?P<album_id>[0-9]+)/$',
        views.album_detail,
        name='album_detail',
    ),
    url(
        r'^album/(?P<album_id>[0-9]+)/favorite/$',
        views.favorite,
        name='favorite_song',
    ),
]

music/models.py
from __future__ import unicode_literals

from django.db import models


class Album(models.Model):
    title = models.CharField(max_length=50)
    artist_id = models.ForeignKey('Artist', on_delete=models.CASCADE)
    genre_id = models.ForeignKey(
        'Genre', blank=True, null=True, on_delete=models.CASCADE)
    album_icon = models.ImageField(blank=True, null=True)

    def __unicode__(self):
        if self.artist_id:
            return self.title + ' by ' + self.artist_id.name
        return self.title


class Artist(models.Model):
    is_band = models.BooleanField(default=True)
    name = models.CharField(max_length=60)

    def __unicode__(self):
        return self.name


class Song(models.Model):
    file_types = [
        ('mp3', 'mp3'),
        ('wav', 'wav'),
        ('flac', 'flac'),
        ('ogg', 'ogg'),
    ]
    title = models.CharField(max_length=60)
    file_type = models.CharField(
        max_length=7, choices=file_types, default='mp3')
    file = models.BinaryField(blank=True, null=True)
    artist_id = models.ForeignKey('Artist', on_delete=models.CASCADE)
    album_id = models.ForeignKey(
        'Album', blank=True, null=True, on_delete=models.CASCADE)
    is_favorite = models.BooleanField(default=False)

    def toggle_favorite(self):
        if self.is_favorite:
            self.is_favorite = False
        else:
            self.is_favorite = True

    def __unicode__(self):
        if self.artist_id and self.album_id:
            return "%s by %s from the album %s" % (
                self.title, self.artist_id.name, self.album_id.title)
        elif self.artist_id and not self.album_id:
            return "%s by %s" % (self.title, self.artist_id.name)
        else:
            return self.title


class Genre(models.Model):
    name = models.CharField(max_length=60)

    def __unicode__(self):
        return self.name

music/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album, Song


def index(request):
    albums = Album.objects.all()
    return render(request, 'music/index.html', {'albums': albums})


def album_detail(request, album_id):
    print "album detail"
    album = get_object_or_404(Album, id=album_id)
    # album = Album.objects.get(id=album_id)
    # return HttpResponse("<h2>Details for album: " + str(album) + "</h2>")
    return render(request, 'music/album_detail.html', {'album': album})


def favorite(request, album_id):
    print "running favorite"
    print "POST: ", request.POST
    album = get_object_or_404(Album, id=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
        print "selected song?: ", selected_song
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/album_detail.html', {
            'album': album,
            'error_message': "YOU SUCK!"
        })
    else:
        print "fav?", selected_song.is_favorite
        selected_song.toggle_favorite()
        print "fav?", selected_song.is_favorite
        selected_song.save()
    return render(request, 'music/album_detail.html', {'album': album})

music/templates/music/album_detail.html
<img src="{{ MEDIA_URL }}{{album.album_icon}}"/>

<h1>{{album.title}}</h1>
<h3><em>by {{album.artist_id.name}}</em></h3>
{% if error_message %}
<h1><strong>{{error_message}}</strong></h1>
{% endif %}
<h4>Songlist: </h4>
<ul>
{% for song in album.song_set.all %}
    <li>{{ song.title }}   type: {{song.file_type}}</li>
    {% endfor %}
</ul>
<form action="{% url 'music:favorite_song' album.id %}" method="POST">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{forloop.counter}}" name="song" value="{{song.id}}">
        <label for="song{{forloop.counter}}">{{song.title}}</label>
    {% if song.is_favorite %} <img style="height: 20px; width: 20px" src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRO3qaVhaDlNE-TII9uqbzJ0E3ypgz0Xb_fvvTaTQACuM99g0931-e42rg"/><br />
    {% endif %}
    {% endfor %}
    <input type="submit" value="Favorite">
</form>

music/templates/music/index.html
{% if not albums %}
<h1>No albums found!</h1>
{% else %}
<h2>ALBUMS: </h2><br />
<ul>
    {% for album in albums %}
    <li>
        <a href="{% url 'music:album_detail' album.id %}"><h4>{{album}}</h4></a>
        <ul>
            {% for song in album.song_set.all %}
            <li>{{song.title}}</li>
            {% endfor %}
        </ul>
    </li>
    {% endfor %}
</ul>
{% endif %}